# upstream eklat {
#     server web:8000;
# }

# server {

#     listen 80;
#     client_max_body_size 500M;
#     location / {
#         proxy_pass http://expertkresel.kg;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header Host $host:1337;
#         proxy_redirect off;
#     }

#     location /static/ {
#         alias /home/app/web/staticfiles/;
#     }
#     location /media/ {
# 	add_header 'Access-Control-Allow-Origin' '*';
#         alias /home/app/web/media/;
#     }
#     location ~ ^/(api/|admin/) {
#       proxy_pass http://expertkresel.kg;      # <= http!
#       proxy_set_header Host $host;
#       proxy_set_header X-Real-IP $remote_addr;
#       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#       proxy_set_header X-Forwarded-Proto $scheme;
#       proxy_http_version 1.1;
#       proxy_redirect off;
#       proxy_read_timeout 60s;
#     }
#     types {
#     font/woff2 woff2;
#     }
# }
upstream eklat {
    server web:8000;
}

server {
    listen 80;
    server_name expertkresel.kg;

    # Фронтенд (React/Vue)
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }

    # Статические файлы Django
    location /static/ {
        alias /home/app/web/staticfiles/;
    }

    # Медиа файлы
    location /media/ {
        add_header 'Access-Control-Allow-Origin' '*';
        alias /home/app/web/media/;
    }

    # API и админка проксируем на Django
    location /api/ {
        proxy_pass http://eklat;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://eklat;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    types {
        font/woff2 woff2;
    }
}
