# Generated by Django 5.1.2 on 2025-01-29 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsOnMainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='categories', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('work_time', models.CharField(max_length=255, verbose_name='Время работы')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('whatsapp', models.CharField(max_length=255, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='ImagesOnAddressAndContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_image', models.ImageField(upload_to='images_on_address', verbose_name='Изображение в адресе')),
                ('contact_image', models.ImageField(upload_to='images_on_address', verbose_name='Изображение в контактах')),
            ],
            options={
                'verbose_name': 'Изображения снизу главной страницы',
                'verbose_name_plural': 'Изображения снизу главной страницы',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='banners', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Главный баннер',
                'verbose_name_plural': 'Главный баннер',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='Цена со скидкой')),
                ('image', models.ImageField(upload_to='products', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description2', models.TextField(verbose_name='Описание2')),
                ('image', models.ImageField(upload_to='repair', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Ремонт кресел',
                'verbose_name_plural': 'Ремонт кресел',
            },
        ),
        migrations.CreateModel(
            name='WorkShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description2', models.TextField(verbose_name='Описание2')),
                ('description3', models.TextField(verbose_name='Описание3')),
                ('description4', models.TextField(verbose_name='Описание4')),
                ('image', models.ImageField(upload_to='workshop', verbose_name='Фоновое изображение')),
            ],
            options={
                'verbose_name': 'Мастерская',
                'verbose_name_plural': 'Мастерская',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='Изображение')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.gallery', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
            },
        ),
    ]
